language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-erase --cover-package=modules

after_success:
  - echo "choose one"

cache: pip

notifications:
  email: false